### PR TITLE
Include total count parameter

### LINKED ISSUE #92: Add support for includeTotalCount query parameter
### Motivation

Allow users to render paging navigation for a list of content items.

### Proposed solution

When the item listing request URL includes the `includeTotalCount` query string parameter, the response contains the total number of content items matching the search criteria. As a result, the client needs only one API call to fetch all information necessary to display a list of content items and the paging navigation.

To return the total number of content items, the `includeTotalCount` parameter must have value `1` or `true` or no value at all.

The total number of content items is returned in the `pagination section` of the response in the `total_count` property. Please note that if the user does not ask for the total item count, this property is not present.

Add support for the `includeTotalCount` parameter and also provide the total number of content items, if available. Also, please provide a warning in documentation comments that asking for the total number of content items might increase the response time and, therefore, users should use it only when they need it.

### Additional context
For a reference implementation please have a look at https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery/QueryParameters/Parameters/IncludeTotalCountParameter.cs

### PR DESCRIPTION
**Pull request by SmootherSpike**
- add totalCount as property in Pagination
- adapt test jackson bindings
- adapt readme

### Motivation

Fixes #92 

### Checklist

- [x] Code follows coding conventions held in this repo
- [x] Automated tests have been added
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

Try the JacksonBindingTest and see if the totalCount property is available

### CODE REVIEW

**Comment by Simply007** [comment]
Hello @SmootherSpike!

Thanks for your pull request. I am going to go through the changes.

I have one question according to t the warning information described in # 92:
> Also, please provide a warning in documentation comments that asking for the total number of content items might increase the response time and, therefore, users should use it only when they need it.

Do you think the information in Javadoc comment for [includeTotalCount](https://github.com/Kentico/kontent-delivery-sdk-java/pull/99/files#diff-2e1649650a7d038ca5b9af42ab9cf115R560) method Is sufficient?

**Comment by SmootherSpike** [comment]
@Simply007 additional text is in the docs now

**Comment by Simply007** [comment]
Great @SmootherSpike!

As a part of digging in the SDK during the review, I started comparing [kontent-java-rx-sdk](https://github.com/Kentico/kontent-java-rx-sdk) and this package and there are not many differences in my opinion.

Would you be willing to jump on a call and discuss a couple of ideas I have to improve the java stack? 
If you are open I am available on [gitter](https://gitter.im/Simply007) and we could continue there.

**Comment by Simply007** [comment]
Fix released in 3.2.0-SNAPSHOT

**Comment by Simply007** [comment]
version 3.2.0 is released!
https://github.com/Kentico/kontent-delivery-sdk-java/releases/tag/3.2.0

**Pull request merged**
