### PR TITLE
#94 add width and height to asset

### LINKED ISSUE #94: Width and Height of Asset model missing
The asset model does not provide the width and height of the image yet, which the api does provide via curl.

Please map those values correctly, we need this information to do our server side rendering correctly

### PR DESCRIPTION
**Pull request by SmootherSpike**
- fix tests after changes

### Motivation

Fixes #94 

### Checklist

- [x] Code follows coding conventions held in this repo
- [x] Automated tests have been added
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### CODE REVIEW

**Comment by petrsvihlik** [comment]
thanks, we'll have a look at it soon :)

**Comment by kentico-timothyf** [comment]
approving changes - will fix CI builds in another PR as they are not caused by this PR, pre-existing issues

Thanks for the PR @SmootherSpike !

**Comment by SmootherSpike** [comment]
@kentico-timothyf Is there already a new version with these changes available?

**Comment by kentico-timothyf** [comment]
@SmootherSpike no, I am going to be working on fixing some issues with tests today and will release a new version, hopefully by end of day 01/31

**Comment by SmootherSpike** [comment]
Any update on the version so far? it is now a week ago, since last comment

**Comment by kentico-timothyf** [comment]
@SmootherSpike I had finished the pending PR's and made changes to finalize the rebrand to Kontent, Just waiting on Adam to do the release now, hopefully will happen early this week I will let you know when it happens in case you miss it!

**Comment by SmootherSpike** [comment]
@kentico-timothyf  @petrsvihlik Any update for a new version, since it is a couple of days right now?

**Comment by aweigold** [comment]
@SmootherSpike I published to nexus last night, should be there.  I gave @kentico-timothyf detailed instructions on how to release as well, and will leave it up to him and @petrsvihlik for release announcements.

**Comment by kentico-timothyf** [comment]
@aweigold thanks for the release! we will do the announcement as soon as everything has propagated to the proper channels so that it shows up everywhere we expect it to, in the meantime @SmootherSpike you can still utilize the release as it is already showing in maven: https://oss.sonatype.org/content/groups/public/com/github/kentico/kontent-delivery/3.1.0/

**Pull request merged**
